-- Run once in Supabase: SQL Editor -> paste -> Run.
-- Timestamps are stored as TEXT 'YYYY-MM-DD HH:MM:SS' in Malaysia time, same as the old SQLite DB.

create or replace function local_now() returns text language sql stable as $$
  select to_char(now() at time zone 'Asia/Kuala_Lumpur', 'YYYY-MM-DD HH24:MI:SS')
$$;

-- Daily progress entries
create table if not exists progress (
  id integer generated by default as identity primary key,
  date text not null,
  category text not null,
  description text not null,
  percentage double precision default 0,
  location text,
  reported_by text,
  photo text,
  photos text,
  created_at text default local_now(),
  updated_at text default local_now()
);

-- Materials tracking
create table if not exists materials (
  id integer generated by default as identity primary key,
  date text not null,
  material_name text not null,
  category text not null,
  quantity double precision not null,
  unit text not null,
  supplier text,
  po_number text,
  delivery_note text,
  received_by text,
  location text,
  photo text,
  photos text,
  status text default 'received',
  notes text,
  created_at text default local_now()
);

-- Issues tracking
create table if not exists issues (
  id integer generated by default as identity primary key,
  date text not null,
  title text not null,
  description text not null,
  category text not null,
  priority text default 'medium',
  status text default 'open',
  location text,
  reported_by text,
  assigned_to text,
  photo text,
  photos text,
  resolution text,
  resolved_at text,
  created_at text default local_now(),
  updated_at text default local_now()
);

-- Work orders / tasks
create table if not exists work_orders (
  id integer generated by default as identity primary key,
  date text not null,
  title text not null,
  description text,
  category text not null,
  priority text default 'medium',
  status text default 'pending',
  assigned_to text,
  due_date text,
  completed_at text,
  notes text,
  created_at text default local_now()
);

-- Labour attendance
create table if not exists attendance (
  id integer generated by default as identity primary key,
  date text not null,
  worker_name text not null,
  contractor text,
  role text,
  status text default 'present',
  hours_worked double precision default 8,
  overtime double precision default 0,
  notes text,
  created_at text default local_now()
);

-- Daily site diary
create table if not exists diary (
  id integer generated by default as identity primary key,
  date text not null unique,
  weather text,
  temperature text,
  visitors text,
  general_notes text,
  safety_notes text,
  created_at text default local_now(),
  updated_at text default local_now()
);

-- Project milestones
create table if not exists milestones (
  id integer generated by default as identity primary key,
  title text not null,
  description text,
  target_date text,
  actual_date text,
  status text default 'pending',
  percentage double precision default 0,
  created_at text default local_now()
);

-- The bot connects with the DB password / service key, so lock the tables
-- away from the public anon API.
alter table progress enable row level security;
alter table materials enable row level security;
alter table issues enable row level security;
alter table work_orders enable row level security;
alter table attendance enable row level security;
alter table diary enable row level security;
alter table milestones enable row level security;
